config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "session#new"
    post "/login", to: "session#create"
    delete "/logout", to: "session#destroy"
    post "/signup",  to: "users#create"
  end
  resources :password_resets, only: %i(new create edit update)
  resources :account_activations, only: %i(edit)
  resources :microposts, only: %i(create destroy)
  resources :relationships, only: %i(create destroy)
  resources :followers, only: %i(show)
  resources :followings, only: %i(show)
  resources :users, only: %i(index show create edit update destroy) do
    get "page/:page", action: :index, on: :collection
  end
 end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new; end

  def create
    user = User.find_by email: params[:session][:email].downcase

    if user&.authenticate(params[:session][:password])
      acc_activated user
    else
      acc_no_activated
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

  def acc_activated user
    log_in user

    if params[:session][:remember_me] == Settings.remember_me
      remember user
    else
      forget user
    end
    redirect_back_or user
  end

  def acc_no_activated
    flash.now[:danger] = t "danger"
    redirect_to root_url
  end
end

app/helpers/session_helper.rb
module SessionHelper
  def log_in user
    session[:user_id] = user.id
  end

  def forget user
    user.forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by id: user_id
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by id: user_id

      if user&.authenticated? cookies[:remember_token]
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete :user_id
    @current_user = nil
  end

  def redirect_back_or default
    redirect_to session[:forwarding_url] || default
    session.delete :forwarding_url
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/views/session/new.html.erb
<% provide :title, t(".login") %>
<h1><%= t ".login" %></h1>
<p><%= t ".login1" %></p>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for :session, url: login_path do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password %>
      <%= link_to t("forgotpassword"), new_password_reset_path %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :remember_me, class: "checkbox inline" do %>
        <%= f.check_box :remember_me %>
        <span><%= t "session.new.remember" %></span>
      <% end %>
      <%= f.submit t(".login"), class: "btn btn-primary" %>
    <% end %>
    <p><%= link_to t(".new_user"), signup_path %></p>
  </div>
</div>